### ISSUE TITLE
Calendar items are duplicated

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Calendar#26]
### Steps to reproduce

1. Start Launcher `develop`
2. Start SignIn `develop`
3. Start Calendar `develop` 
4. Sign in with user that is member of "Admin (Calendar)" group
5. Go to `http://localhost:8080/launcher/settings`
6. In "Calendar Settings" section add some calendars
7. Go to `http://localhost:8080/Calendar`
8. Create some events
9. Go to `http://localhost:8080/launcher/settings`
10. Go to `http://localhost:8080/Calendar`

### Expected result
Calendar shows correct number of "calendars" and "events"

### Actual result
Calendar shows dupplicated "calendars" and "events";

##### Involved apps' version

- StarcounterPrefabs/Calendar@fcdcc74a02b3626d40000f3d17eb5de59bf05cb2

##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1625378/23027656/fadb6f44-f475-11e6-960c-ace78146c5d7.png)

**Comment by warpech** [comment]
Thank you @un-tone for finding and reporting this. Can you assign this to yourself, or do you need help?

**Comment by un-tone** [comment]
It would be great to get any help with this issue. There are strange "add" operations for calendars and events:
![image](https://cloud.githubusercontent.com/assets/1625378/25663287/ead751e0-301f-11e7-8959-2b7b6881237f.png)

I can also note that it works correctly without a running Launcher.

**Comment by warpech** [comment]
I've spent half day investigating this.

There is a simpler way to reproducing it now:

1. Start Calendar `create-initial-data` branch
2. Start Launcher `develop` branch
3. Start SignIn `develop` branch
4. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
5. Go to `http://localhost:8080/Calendar/render`
6. Click on the Settings icon in the top right corner
7. Click on the Calendar link in the left menu

The same problem with incorrect patch appears at this point.

The problematic patches are:

- operation `add` at path `/workspaces/0/Calendar/CurrentPage/Calendars/0`
- operation `add` at path `/workspaces/0/Calendar/CurrentPage/events/0`
- operation `add` at path `/workspaces/0/Calendar/CurrentPage/selectedReservation/Calendars/0
`

Instead of these patches, we would expect operation `replace` at path `/workspaces/0/Calendar/CurrentPage/Calendars`

These replace operations are triggered by the getters in the view-model at lines https://github.com/StarcounterApps/Calendar/blob/f8421140669e8e2de938da6c8b6b9cdb81366d7f/src/Calendar/ViewModels/EventsPage.json.cs#L20-L26.

@chrhol please take a look, this looks like a serious bug in Puppeteer.

**Comment by chrhol** [comment]
I have reproduced it, and I have no answer yet to why the rows gets duplicated in this case. Something strange is happening.

However, I found one place in the calendar app where it gets blended with the incorrect page and it's the old confusion as to what to return as response from a handler.

If [this line](https://github.com/StarcounterApps/Calendar/blob/create-initial-data/src/Calendar/Api/Settings_GET.cs#L30) in `Settings_GET.cs` is changed from `return master;` to `return master.CurrentPage;` it works as expected. It's the settingspage that should be blended for this uri, not the master.

I will investigate a little more though, I want to know why the item is duplicated. Maybe it's because master is inserted in several places.

**Comment by chrhol** [comment]
So the problem is that the same viewmodel instance (`MasterPage`) is returned both as workspace and as the settings page (i.e. a `Self.GET()` from Launcher to `CurrentPage`).

This is not handled correctly and messes a lot of things up. I see no easy and/or quick way to fix this. We need to redo some of the core functionallity around this.

So short-term workaround I would say would be to return different instances for settings and workspace (the same type is fine, just not the same instance).

Long term, it goes back partly to the session discussion and what we came up with there (https://github.com/Starcounter/level1/issues/4159) and partly with the changes needed to support a more correct pattern (multiple codehosts and orchestrator/blender/dispatcher)

**Comment by un-tone** [comment]
Thanks @warpech and @chrhol 
The issue is fixed in the PR https://github.com/StarcounterApps/Calendar/pull/42

**Comment by un-tone** [comment]
Closing as done.
